### ISSUE TITLE
Error when trying to write crontab

### ISSUE THREAD

**Issue by thinhpc** [boboldehampsink/cronjob#3]
I got this error and don't know why.
I created success many crontab before this error occur.
And maybe it's reach limit crontab size, it's about ~ 500 process lines then it's error.

`PHP Fatal error:  Uncaught exception 'DomainException' with message 'Error when trying to write crontab : ' in /home/ezsecure/api/crontab/CrontabAdapter.php:114
Stack trace:
#0 /home/ezsecure/api/crontab/CrontabRepository.php(161): TiBeN\CrontabManager\CrontabAdapter->writeCrontab('MAILTO=""\n47 23...')
#1 /home/ezsecure/api/util/Utils.php(465): TiBeN\CrontabManager\CrontabRepository->persist()
#2 [internal function]: TestPR\Utils::createCronJob(Array, true, 'fast')
#3 /home/ezsecure/api/util/Utils.php(304): call_user_func_array('\\TestPR\\Utils::...', Array)
#4 /home/ezsecure/api/util/Utils.php(665): TestPR\Utils::lockFunction('\\TestPR\\Utils::...', Array, 'lockCrontab')
#5 /home/ezsecure/api/start.php(41): TestPR\Utils::makeCrontabforUser(Array)
#6 {main}
  thrown in /home/ezsecure/api/crontab/CrontabAdapter.php on line 114`

How can I fix this?

**Comment by boboldehampsink** [comment]
This looks like a problem with the underlying framework. I suggest you look for a solution at https://github.com/TiBeN/CrontabManager
